server:
  port: 8083
  servelet:
    context-path: /auth

spring:
  application:
    name: auth
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/auth?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: sa
    password: 9202157

security:
  jwt:
    token:
      secret-key: chave_microservices
      expire-length: 360000

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/registry/eureka